# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Touch
      shell: bash
      run: |
        mkdir -p ./dist/FluidSynthPlugin.vst3.${{ matrix.os }} 
        touch ./dist/FluidSynthPlugin.vst3.${{ matrix.os }}/hello-${{ matrix.os }}.text

    - name: Upload Built Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: FluidSynthPlugin.vst3.${{ matrix.os }}
        path: ./dist/FluidSynthPlugin.vst3.${{ matrix.os }}
        retention-days: 7
    
########################################################################################################################

  release:
    name: Create GitHub Release
    needs: build 
    runs-on: ubuntu-latest

    steps:
    - name: Download All Built Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./dist

    - name: Archive Release
      shell: bash 
      run: |
        for dir in ./dist/*/; do zip -r "${dir%/}.zip" "$dir"; done
        ls ./dist/

    # - name: Create GitHub Release
    #   id: create_release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     tag_name: ${{ github.ref_name }}
    #     release_name: Release ${{ github.ref_name }}
    #     draft: false
    #     prerelease: false
    #     files: FluidSynthPlugin.vst3.${{ steps.variables.outputs.build-os }}.zip

    # - name: Show Release URL
    #   run: echo "Release created at ${{ steps.create_release.outputs.url }}"
